In [41]:
import pandas as pd

In [42]:
csv_name = "tmp5c00jrqx.csv"
df = pd.read_csv(csv_name)

In [43]:
years = [2019]
offense_codes = ["413", "3301", "802", "311"]

df = df[df["YEAR"].isin(years) & df["OFFENSE_CODE"].isin(offense_codes)]
df

,INCIDENT_NUMBER,OFFENSE_CODE,OFFENSE_CODE_GROUP,OFFENSE_DESCRIPTION,DISTRICT,REPORTING_AREA,SHOOTING,OCCURRED_ON_DATE,YEAR,MONTH,DAY_OF_WEEK,HOUR,UCR_PART,STREET,Lat,Long,Location
11,I192078645,3301,Verbal Disputes,VERBAL DISPUTE,B3,450,NaN,2019-09-29 06:00:00,2019,9,Sunday,6,Part Three,ASPINWALL RD,42.291816,-71.072441,"(42.29181580, -71.07244098)"
18,I192078635,3301,Verbal Disputes,VERBAL DISPUTE,B3,466,NaN,2019-09-28 23:55:00,2019,9,Saturday,23,Part Three,GOODALE RD,42.283628,-71.093496,"(42.28362830, -71.09349553)"
20,I192078632,3301,Verbal Disputes,VERBAL DISPUTE,B3,429,NaN,2019-09-29 00:33:00,2019,9,Sunday,0,Part Three,HARWOOD ST,42.285765,-71.087632,"(42.28576510, -71.08763245)"
22,I192078624,3301,Verbal Disputes,VERBAL DISPUTE,B2,311,NaN,2019-09-29 00:19:00,2019,9,Sunday,0,Part Three,MAYWOOD ST,42.317859,-71.081036,"(42.31785924, -71.08103560)"
28,I192078613,802,Simple Assault,ASSAULT SIMPLE - BATTERY,A7,17,NaN,2019-09-29 02:30:00,2019,9,Sunday,2,Part Two,CHELSEA ST,42.379124,-71.028082,"(42.37912370, -71.02808210)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
437287,192078723,3301,NaN,VERBAL DISPUTE,B2,261,0,2019-09-29 12:35:00,2019,9,Sunday,12,NaN,W COTTAGE ST,NaN,NaN,"(0.00000000, 0.00000000)"
437293,192078712,3301,NaN,VERBAL DISPUTE,C11,364,0,2019-09-29 12:35:00,2019,9,Sunday,12,NaN,LESLIE ST,NaN,NaN,"(0.00000000, 0.00000000)"
437294,192078711,3301,NaN,VERBAL DISPUTE,B2,911,0,2019-09-29 12:42:00,2019,9,Sunday,12,NaN,RUGGLES ST,NaN,NaN,"(0.00000000, 0.00000000)"
437306,192078690,3301,NaN,VERBAL DISPUTE,C11,69,0,2019-09-29 10:38:00,2019,9,Sunday,10,NaN,CHARLES ST,NaN,NaN,"(0.00000000, 0.00000000)"
437310,192078682,3301,NaN,VERBAL DISPUTE,C11,387,0,2019-09-29 10:21:00,2019,9,Sunday,10,NaN,MEDWAY ST,NaN,NaN,"(0.00000000, 0.00000000)"

In [44]:
groups = df.groupby(["YEAR", "DISTRICT", "OFFENSE_CODE"]).groups

groups.items()

dict_items([((2019, 'B3', 3301), Int64Index([    11,     18,     20,     65,    103,    122,    229,    343,
               363,    420,
            ...
            436655, 436696, 436702, 436709, 436734, 436893, 436980, 437108,
            437165, 437174],
           dtype='int64', length=858)), ((2019, 'B2', 3301), Int64Index([    22,     64,    123,    300,    379,    555,    642,    645,
               769,    856,
            ...
            436959, 437029, 437031, 437045, 437256, 437257, 437258, 437265,
            437287, 437294],
           dtype='int64', length=930)), ((2019, 'A7', 802), Int64Index([   28,    40,   331,   346,   706,   717,   973,  1690,  1764,
             3696,
            ...
            65128, 65298, 65452, 66080, 67279, 68983, 69213, 70014, 70557,
            71547],
           dtype='int64', length=134)), ((2019, 'C11', 413), Int64Index([   46,   792,   887,  2137,  2489,  3094,  3438,  3989,  4184,
             4439,
            ...
            69869, 70427, 71013, 71345, 71589, 72367, 73306, 73979, 74010,
            74153],
           dtype='int64', length=145)), ((2019, 'C11', 3301), Int64Index([    62,     89,    280,    311,    394,    651,    726,    853,
               892,   1309,
            ...
            436299, 436320, 436729, 436850, 436968, 437155, 437189, 437293,
            437306, 437310],
           dtype='int64', length=768)), ((2019, 'B2', 802), Int64Index([    67,    201,    256,    413,    676,    710,    737,    778,
               903,   1079,
            ...
             72814,  72950,  73159,  73177,  73399,  73557,  73970,  74064,
             97408, 128575],
           dtype='int64', length=521)), ((2019, 'E5', 3301), Int64Index([    71,    147,    263,   1538,   2976,   3066,   4192,   4320,
              6082,   6480,
            ...
            435806, 435851, 436330, 436519, 436691, 436719, 436742, 436876,
            437166, 437285],
           dtype='int64', length=217)), ((2019, 'B3', 413), Int64Index([   73,   606,   815,   888,  1366,  2783,  2814,  2828,  2878,
             3231,
            ...
            68163, 68898, 70360, 70379, 70847, 70911, 71294, 72641, 73963,
            74171],
           dtype='int64', length=151)), ((2019, 'B3', 802), Int64Index([    75,    301,    359,    669,    698,    704,    816,    918,
               996,   1029,
            ...
             71297,  71370,  71620,  71626,  71981,  72315,  72699,  73009,
             73020, 137478],
           dtype='int64', length=397)), ((2019, 'C6', 802), Int64Index([   97,   198,   349,   447,   448,   449,   615,   678,   756,
             1442,
            ...
            71392, 71510, 71680, 72003, 73384, 73430, 73629, 73824, 73847,
            74134],
           dtype='int64', length=282)), ((2019, 'C11', 802), Int64Index([  104,   196,   211,   305,   540,  1199,  1487,  1950,  2019,
             2208,
            ...
            71586, 71673, 71845, 72369, 72995, 73502, 73625, 73931, 74124,
            74126],
           dtype='int64', length=442)), ((2019, 'C6', 413), Int64Index([  105,   617,  1441,  2440,  2518,  4047,  4319,  5118,  5722,
             6022,
            ...
            63227, 63418, 63582, 66347, 67618, 67838, 68390, 70277, 73129,
            74201],
           dtype='int64', length=101)), ((2019, 'E5', 413), Int64Index([  107,   523,  3032,  4487,  4569,  5179, 15752, 25394, 25795,
            31454, 31787, 31822, 33944, 33958, 35543, 38783, 43044, 43925,
            46448, 48322, 48499, 53776, 54104, 58796, 64516, 72763],
           dtype='int64')), ((2019, 'A1', 802), Int64Index([   134,    269,    393,    894,    982,   1032,   1057,   1240,
              1431,   1518,
            ...
             73680,  73711,  73733,  74076,  74145,  74203,  74218,  74225,
             75831, 145168],
           dtype='int64', length=589)), ((2019, 'D4', 802), Int64Index([   152,    852,   1212,   1250,   1596,   1786,   2055,   2074,
              2173,   2536,
            ...
             72885,  73040,  73180,  73229,  73944,  73997,  74183,  74220,
            153746, 164082],
           dtype='int64', length=503)), ((2019, 'D4', 311), Int64Index([  202,   518,  4082,  5635, 20765, 25716, 25792, 31091, 52678,
            58260, 58486, 63120, 65799, 69803, 70838],
           dtype='int64')), ((2019, 'E13', 802), Int64Index([  214,   320,   975,  1806,  1930,  2067,  2230,  2523,  2821,
             3303,
            ...
            68405, 68774, 68842, 69034, 69874, 72691, 72727, 73477, 73506,
            73955],
           dtype='int64', length=147)), ((2019, 'A7', 413), Int64Index([  261,   531,  3160,  3621,  3720,  4440,  4506,  7069,  9796,
            10108, 11454, 11944, 12546, 14484, 14502, 14641, 18654, 20868,
            22116, 24745, 24960, 29246, 29636, 30067, 38064, 38065, 42320,
            42355, 44685, 47150, 51255, 52292, 56213, 57059, 57827, 58679,
            62176, 62306, 64556, 64750, 66890, 67721, 70008, 72739],
           dtype='int64')), ((2019, 'A1', 3301), Int64Index([   262,    694,   1862,   2889,   5569,   8466,   9375,  10310,
             10848,  13366,  14931,  15412,  18206,  20328,  21568,  21576,
             22436,  24102,  29476,  31974,  33360,  34950,  40609,  40787,
             42316,  44207,  45174,  49153,  49935,  52083,  52135,  52686,
             54922,  58933,  59010,  62553,  64000,  67273,  70372,  71030,
             73382, 125954, 328821, 361083, 428398, 429261, 430146, 430472,
            431541, 432058, 432116, 432916, 433448, 434408, 435658, 435918,
            435945, 436329, 436418, 436654, 436940],
           dtype='int64')), ((2019, 'D4', 413), Int64Index([  274,   851,  1087,  2502,  3388,  3697,  3984,  4419,  4459,
             4696,
            ...
            64115, 64497, 65213, 65247, 69315, 70140, 70833, 71574, 72921,
            97454],
           dtype='int64', length=113)), ((2019, 'A1', 413), Int64Index([   278,    328,    877,   2405,   2710,   3013,   3074,   3137,
              3722,   4056,
            ...
             71026,  71031,  72862,  72874,  73590,  73592,  73754,  74202,
            100328, 149944],
           dtype='int64', length=165)), ((2019, 'E13', 413), Int64Index([  293,  1495,  1524,  3561,  4029,  4339,  4457,  5383,  7514,
             8242,  8716,  8999,  9006,  9007, 13168, 14117, 16906, 17434,
            17760, 17761, 17999, 19183, 19197, 19210, 22865, 23321, 23821,
            24542, 25148, 25282, 25691, 25991, 26377, 28314, 28741, 29357,
            30472, 32162, 32286, 33998, 34122, 36062, 37065, 37111, 37545,
            39375, 40898, 41411, 43370, 49464, 50541, 52743, 55258, 55270,
            55569, 55598, 56724, 57309, 58944, 61467, 62822, 63385, 64916,
            66850, 67058, 68055, 71711, 73520],
           dtype='int64')), ((2019, 'D14', 3301), Int64Index([   330,    656,    992,   1933,   2224,   2880,   3138,   3191,
              4353,   5185,
            ...
            435451, 435942, 435994, 436047, 436183, 436208, 436332, 436474,
            436618, 437041],
           dtype='int64', length=152)), ((2019, 'A7', 3301), Int64Index([   334,    485,   2338,   3233,   3431,   3436,   4098,   5510,
              6571,   7511,
            ...
            435278, 435455, 435857, 435970, 436311, 436579, 436680, 436969,
            437021, 437276],
           dtype='int64', length=133)), ((2019, 'E18', 3301), Int64Index([   367,    684,   1141,   1731,   2249,   2371,   2684,   2689,
              2992,   3034,
            ...
            436052, 436481, 436535, 436606, 436668, 436825, 436864, 436955,
            437203, 437250],
           dtype='int64', length=350)), ((2019, 'E5', 802), Int64Index([  368,   957,  1516,  1851,  2490,  3033,  3481,  3588,  3852,
             4104,
            ...
            67071, 67625, 69086, 69932, 70159, 70941, 71718, 72151, 73305,
            73603],
           dtype='int64', length=135)), ((2019, 'D14', 413), Int64Index([   474,   1094,   2386,   3623,   8721,   9199,  12709,  13393,
             17366,  18113,  21286,  23240,  26911,  31209,  31281,  31837,
             36286,  36403,  37984,  39724,  40788,  40805,  41703,  44538,
             45722,  46294,  48927,  55506,  55941,  59514,  59761,  62394,
             62619,  63357,  68122,  69545,  69864,  73222, 230428],
           dtype='int64')), ((2019, 'A15', 802), Int64Index([  699,  1562,  3174,  4066,  9535,  9545, 11618, 13284, 14462,
            16984, 17515, 17802, 18763, 18862, 19104, 20712, 20808, 20824,
            22330, 22568, 23253, 26296, 26416, 26760, 28024, 28848, 31913,
            33544, 34794, 36783, 37607, 39204, 40648, 41541, 41593, 43866,
            45459, 45791, 47778, 48011, 48797, 51939, 53208, 53641, 54065,
            54300, 54354, 57781, 58203, 58254, 59283, 60303, 61712, 62936,
            63298, 64160, 64413, 67393, 72035, 72661],
           dtype='int64')), ((2019, 'E13', 3301), Int64Index([   787,   1895,   1965,   2342,   2727,   2820,   3090,   3268,
              3952,   4027,
            ...
            435662, 435756, 436343, 436467, 436529, 436676, 436773, 437034,
            437248, 437280],
           dtype='int64', length=204)), ((2019, 'B2', 413), Int64Index([   874,   1484,   1548,   2639,   2680,   2705,   2982,   3205,
              3347,   3349,
            ...
             70565,  70603,  70722,  71036,  71059,  71338,  71815,  71821,
             71952, 139034],
           dtype='int64', length=276)), ((2019, 'D14', 802), Int64Index([   960,   1086,   1577,   1586,   1876,   1957,   2089,   2124,
              2143,   2402,
            ...
             71333,  71528,  72478,  72864,  72891,  73221,  73576,  73679,
             74063, 230426],
           dtype='int64', length=186)), ((2019, 'E18', 802), Int64Index([  983,  1172,  1705,  2454,  3838,  4127,  4161,  4536,  4599,
             4600,
            ...
            71442, 72166, 72930, 73422, 73725, 73926, 73950, 73971, 73984,
            74214],
           dtype='int64', length=137)), ((2019, 'A15', 3301), Int64Index([  1204,   1649,   2102,   6551,   6913,   7247,   7407,  12553,
             12824,  15896,  16814,  17647,  18661,  19448,  19792,  21284,
             27506,  30828,  37676,  38649,  40838,  43111,  45572,  46078,
             46703,  47705,  53823,  57808,  58428,  60721,  63574,  67869,
             68812,  69244,  70250,  73703, 427490, 427673, 428005, 428179,
            428650, 428753, 428756, 428890, 431073, 431315, 431606, 432313,
            433421, 433741, 434210, 435246, 435799],
           dtype='int64')), ((2019, 'A1', 311), Int64Index([1290, 3134, 33052, 35557], dtype='int64')), ((2019, 'D4', 3301), Int64Index([  1398,   2008,   2025,   2283,   2413,   2707,   2864,   2896,
              3585,   3876,
            ...
            435497, 435641, 436405, 436667, 436677, 436800, 436866, 436917,
            437010, 437033],
           dtype='int64', length=235)), ((2019, 'E18', 413), Int64Index([ 1951,  6545,  6993,  7868, 14900, 15307, 16774, 18339, 19536,
            21869, 22523, 22857, 23076, 25598, 25634, 26541, 27260, 27274,
            29806, 30674, 32244, 32531, 34774, 34799, 34817, 37379, 39070,
            40565, 41807, 42424, 42965, 44279, 45048, 49950, 49956, 51759,
            54176, 54371, 55741, 55752, 56780, 56841, 59443, 62238, 62576,
            64192, 69406, 70071, 70913, 71092, 71441, 71555, 72895, 73126],
           dtype='int64')), ((2019, nan, 802), Int64Index([2009, 11853, 15956, 21756, 37970, 40124, 50579, 64841], dtype='int64')), ((2019, nan, 413), Int64Index([2220, 30146, 67622], dtype='int64')), ((2019, 'A15', 413), Int64Index([ 2839,  3734,  8480,  9334, 11563, 38837, 45645, 46723, 47914,
            55173, 56150, 56167, 62452, 70313],
           dtype='int64')), ((2019, 'C6', 3301), Int64Index([  2846,   3059,   3301,   5255,   5461,   6066,   7746,   8089,
              8880,   9304,
            ...
            434918, 435154, 436142, 436241, 436296, 436398, 436491, 436572,
            436930, 436974],
           dtype='int64', length=176)), ((2019, 'B3', 311), Int64Index([ 3128,  3731,  4260,  4261,  9604,  9624, 16030, 18906, 41003,
            44153, 51777, 68161, 69129],
           dtype='int64')), ((2019, 'B2', 311), Int64Index([ 4980, 17660, 17854, 37617, 37726, 39512, 45765, 47694, 53025,
            53371, 60107, 60564, 62548, 64659],
           dtype='int64')), ((2019, 'E5', 311), Int64Index([5466, 12108, 49762, 69128, 69140, 71571], dtype='int64')), ((2019, 'C11', 311), Int64Index([6479, 31907, 40430, 45152, 51578, 65191, 71606, 73242, 73487], dtype='int64')), ((2019, 'E18', 311), Int64Index([9276, 10810, 23250, 37090, 42058, 52342, 65718, 68443, 69517], dtype='int64')), ((2019, nan, 3301), Int64Index([ 11581,  31112, 346859, 429936, 430360, 430506, 433664, 434376,
            435285, 436070, 436122],
           dtype='int64')), ((2019, 'A7', 311), Int64Index([15580, 34138, 37734, 52163], dtype='int64')), ((2019, 'E13', 311), Int64Index([19199, 56146], dtype='int64')), ((2019, 'D14', 311), Int64Index([36282, 67112], dtype='int64')), ((2019, 'C6', 311), Int64Index([43304], dtype='int64')), ((2019, 'External', 3301), Int64Index([427433, 434932], dtype='int64'))])

In [46]:
counts = {}
for name, group in groups.items():
    counts[name] = len(group)

counts

{(2019, 'B3', 3301): 858,
 (2019, 'B2', 3301): 930,
 (2019, 'A7', 802): 134,
 (2019, 'C11', 413): 145,
 (2019, 'C11', 3301): 768,
 (2019, 'B2', 802): 521,
 (2019, 'E5', 3301): 217,
 (2019, 'B3', 413): 151,
 (2019, 'B3', 802): 397,
 (2019, 'C6', 802): 282,
 (2019, 'C11', 802): 442,
 (2019, 'C6', 413): 101,
 (2019, 'E5', 413): 26,
 (2019, 'A1', 802): 589,
 (2019, 'D4', 802): 503,
 (2019, 'D4', 311): 15,
 (2019, 'E13', 802): 147,
 (2019, 'A7', 413): 44,
 (2019, 'A1', 3301): 61,
 (2019, 'D4', 413): 113,
 (2019, 'A1', 413): 165,
 (2019, 'E13', 413): 68,
 (2019, 'D14', 3301): 152,
 (2019, 'A7', 3301): 133,
 (2019, 'E18', 3301): 350,
 (2019, 'E5', 802): 135,
 (2019, 'D14', 413): 39,
 (2019, 'A15', 802): 60,
 (2019, 'E13', 3301): 204,
 (2019, 'B2', 413): 276,
 (2019, 'D14', 802): 186,
 (2019, 'E18', 802): 137,
 (2019, 'A15', 3301): 53,
 (2019, 'A1', 311): 4,
 (2019, 'D4', 3301): 235,
 (2019, 'E18', 413): 54,
 (2019, nan, 802): 8,
 (2019, nan, 413): 3,
 (2019, 'A15', 413): 14,
 (2019, 'C6', 3301): 176,
 (2019, 'B3', 311): 13,
 (2019, 'B2', 311): 14,
 (2019, 'E5', 311): 6,
 (2019, 'C11', 311): 9,
 (2019, 'E18', 311): 9,
 (2019, nan, 3301): 11,
 (2019, 'A7', 311): 4,
 (2019, 'E13', 311): 2,
 (2019, 'D14', 311): 2,
 (2019, 'C6', 311): 1,
 (2019, 'External', 3301): 2}